# Projet 02 :  méthode de Gauss-Jordan

La méthode de Gauss-Jordan est une technique de résolution de systèmes d'équations linéaires:

\begin{equation}
\left(
\begin{array}{c c c c}
a_{0,0}   & a_{0,1}   & \cdots & a_{0,n-1} \\
a_{1,0}   & a_{1,1}   & \cdots & a_{1,n-1} \\
\vdots         & \vdots         & \ddots & \vdots \\
a_{n-1,0} & a_{n-1,1} & \cdots & a_{n-1,n-1} 
\end{array}
\right)
\left(
\begin{array}{c}
x_0 \\ x_1 \\ \vdots \\ x_{n-1}
\end{array}
\right)
=
\left(
\begin{array}{c}
b_0 \\ b_1 \\ \vdots \\ b_{n-1}
\end{array}
\right)
\end{equation}


Elle consiste à transformer la matrice associée $A=(a_{ij})_{\; 0\leq i < n,\;  0\leq j < n }$ en une matrice unité en effectuant des combinaisons linéaires de lignes.
Cette variante de la méthode de Gauss permet de calculer l'inverse d'une matrice.

### Matrice augmentée

Soient $A$ et $B$ deux matrices  ayant le même nombre de lignes, on appelle matrice augmentée la matrice $(A | B)$ formée des deux blocs $A$ et $B$ mis côte à côte.

Cette notion est très pratique lorsqu'on veut résoudre le système d'équations avec différents seconds
membres. La matrice $B$ est alors construite en accollant à droite de $A$, les vecteurs colonnes formant les seconds membres.
Elle se réduit naturellement à un vecteur dans le cas d'un seul second membre.

## 1. Algorithme de base sans changement de pivot 

On augmente la matrice $A$ avec le(s) vecteur(s) colonne(s) du second membre.
On vérifie que $\forall i,  a_{ii} \neq 0$ sinon effectue des échanges de lignes. 

L'algorithme est itératif et s'effectue en $n$ étapes. A l'étape $k \in [0, n[$, on
combine toutes les lignes sauf la ligne k pour faire apparaître des $0$ sur toute
la colonne $k$ sauf au niveau du pivot $a_{kk}$.

pour k=0 à n-1:
1. diviser la ligne $k$ de la matrice $A$ par $a_{kk}$
2. pour i=0 à n-1 sauf k, retrancher à la ligne i, la nouvelle ligne k multipliée par $a_{ik}$ 

Après résolution, la matrice $A$ apparait comme la concaténation de la matrice
identité, accolée aux solutions $x$ du système.

### Exemple pratique

Soit à résoudre:
\begin{array}{l c r}
2x+y-4z & = & 8 \\
3x+3y-5z & = & 14 \\
4x+5y-2z & = & 16 \\
\end{array}

La matrice augmentée $A^{(0)}$ s'écrit :
\begin{equation}
A^{(0)}=
\left(
\begin{array}{c c c c }
2  & 1   & -4  \\
3  & 3   & -5   \\
4  & 5  & -2  \\ 
\end{array}
\right|
\left.
\begin{array}{c}
8  \\ 14   \\ 16  \\ 
\end{array}
\right)
\end{equation}

Divisons la première ligne par le pivot $a_{0,0}$ :
$l_0 \leftarrow {1 \over 2} \times l_0$

\begin{equation}
A^{(1)}=
\left(
\begin{array}{c c c c }
1  & {1/2}   & -2  \\
0  &  {3/2}   & 1   \\
0  & 3  & 6  \\ 
\end{array}
\right|
\left.
\begin{array}{c}
4   \\ 2    \\ 0  \\ 
\end{array}
\right)
\begin{array}{c}
   \\ l_1 \leftarrow l_1 -3 \times l_0   \\ l_2 \leftarrow l_2 -4 \times l_0  \\ 
\end{array}
\end{equation}

Divisons la deuxième ligne par le pivot $a_{11}$ :
$l_1 \leftarrow {2 \over 3} \times l_1$

\begin{equation}
A^{(2)}=
\left(
\begin{array}{c c c c }
1  & 0   & -7/3  \\
0  & 1   & 2/3   \\
0  & 0  &  4  \\ 
\end{array}
\right|
\left.
\begin{array}{c}
{10/3}   \\ {4/3}    \\ -4  \\ 
\end{array}
\right)
\begin{array}{c}
l_0 \leftarrow  l_0 -{1 \over 2}  \times l_1   \\     \\ l_2 \leftarrow  l_2 -3 \times l_1  \\ 
\end{array}
\end{equation}

Divisons la troisième ligne par le pivot $a_{2,2}$ : $l_2 \leftarrow {1 \over 4} \times l_2$

\begin{equation}
A^{(3)}=
\left(
\begin{array}{c c c c }
1  & 0   & 0  \\
0  & 1   & 0   \\
0  & 0  &  1  \\ 
\end{array}
\right|
\left.
\begin{array}{c}
1   \\ 2    \\ -1  \\ 
\end{array}
\right)
\begin{array}{c}
l_0 \leftarrow  l_0 +{7 \over 3}  \times l_2   \\   l_1 \leftarrow  l_1 - {2 \over 3} \times l_2   \\  \\ 
\end{array}
\end{equation}

La solution se trouve dans la quatrième colonne. Vérifier que $x=\left(1, 2, -1 \right)^t$ est bien solution.

Un code permettant la résolution de Gauss Jordan sans changement de pivot est présenté ci-dessous.
1. Complétez le code proposé pour la fonction 'gauss_jordan' en implémentant l'algorithme présenté.
2. Utilisez la matrice A et le second membre L donnés dans l'exemple pour calculer le résultat R grâce à la fonction 'gauss-jordan'. Vérifiez le résulat obtenu en calculant le résidu : $L-A @ R$, qui doit être nul
3. Confirmez le résultat avec la fonction `numpy.linalg.solve()`.

In [14]:
import numpy as np
import math
np.set_printoptions(precision=4, suppress=True)

def gauss_jordan(A, B):
    n=A.shape[0]
    assert A.shape[1]==n, 'number of columns not equal to %r' % n
    assert B.shape[0]==n, 'number of rows not equal to %r' % n

    A=np.hstack((A, B)) # concaténation
    
    for k in range(n):
        # step 1.
        akk=A[k, k]
        A[k, :]=A[k, :]/akk

        # step 2.
        for i in range(n):
            if i==k: continue
            aik=A[i, k]
            A[i, :]=A[i, :]-aik*A[k, :]
            
    R=A[:, n:]
    return R

# np.matrix est obsolete
# K=np.matrix([[2, 1, -4], [3, 3, -5], [4, 5, -2]], dtype=float)
# L=np.matrix([[8], [14], [16]], dtype=float)

K = np.array([[2, 1, -4], 
              [3, 3, -5], 
              [4, 5, -2]], dtype=float)

L = np.array([8, 14, 16], dtype=float).reshape(-1, 1)

R=gauss_jordan(K, L)
print(R)
print('Residu ----------')
print(L-(K @ R))
// ou encore
// print(L-K.dot(R))
print('solution donnée par numpy.linalg')
print(np.linalg.solve(K,L))

[[ 1.]
 [ 2.]
 [-1.]]
Residu ----------
[[0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]]
solution donnée par numpy.linalg
[[ 1.]
 [ 2.]
 [-1.]]


## 2. Inversion d'une matrice

Pour inverser une matrice, il suffit d'utiliser comme second membre la matrice identité (peut être créée avec `np.eye(N)`). Testez cela avec la matrice de votre choix. Pour vérifier la validité de votre solution, vous pouvez utiliser la fonction `numpy.linalg.inv()`.

In [4]:
Id = np.eye(3)
R = gauss_jordan(K, Id)
print(R)
print('numpy solution:')
print(np.linalg.inv(K))

[[ 1.5833 -1.5     0.5833]
 [-1.1667  1.     -0.1667]
 [ 0.25   -0.5     0.25  ]]
numpy solution:
[[ 1.5833 -1.5     0.5833]
 [-1.1667  1.     -0.1667]
 [ 0.25   -0.5     0.25  ]]


## 3. Stabilité numérique

SSi le pivot est trop faible, on peut rencontrer des problèmes de stabilité numérique. 

1. Utiliser l'exemple ci-dessous pour mettre ces problèmes en évidence.
2. Ecrire une nouvelle version de 'gauss_jordan' avec un paramètre supplémentaire, permettant d'activer l'affichage de la matrice lors des étapes intermédiaires.
3. Analyser les matrices intermédiaires pour comprendre ce qui pose problème avec l'exemple proposée.

In [16]:
K=np.array([[1, 1/4,  0, 0], 
            [1, 5/4, 12, 0], 
            [1, 1/3,  1, 1], 
            [1, 5/4, 13, 1]], dtype=float)
L=np.array([[0], [0], [1], [0]])

R=gauss_jordan(K, L)
print(R)
print('Residu ----------')
print(L-(K @ R))

[[-4.]
 [16.]
 [-1.]
 [ 1.]]
Residu ----------
[[ 0.    ]
 [-4.    ]
 [-0.3333]
 [-4.    ]]


Dans l'exemple précédent, on observe un résidu non-nul, ce qui prouve que l'on n'a pas calculé correctement la solution. L'erreur observée est due à un pivot dont la valeur est très proche de 0, ce qui provoque des erreurs numériques quand on divise par le pivot. Ce problème peut être détecté lors du calcul. Une façon d'éviter de retourner un résultat de calcul faux est d'utiliser les exceptions comme proposé ci-après.

On émettra une exception si le pivot $|a_{k,k}|< \epsilon \approx 10^{-6}$.Pour ce faire on utilisera l'instruction `raise` dans la fonction 'gauss_jordan' pour lancer une exception de type `ZeroDivisionError`. On récupérera cette exception grace à un bloc `try / except` lors de l'appel de la fonction

In [2]:
import numpy as np
import math

def gauss_jordan(A, B):
    n=A.shape[0]
    assert A.shape[1]==n, 'number of columns not equal to %r' % n
    assert B.shape[0]==n, 'number of rows not equal to %r' % n

    A=np.hstack((A, B)) # concaténation
    epsilon=1e-6
    
    for k in range(n):
        akk=A[k, k]
        if abs(akk)<epsilon:
            raise ZeroDivisionError("pivot akk trop faible")
        A[k, :]=A[k, :]/akk
        
        for i in range(n):
            if i==k: continue
            aik=A[i, k]
            A[i, :]=A[i, :]-aik*A[k, :]

    R=A[:, n:]
    return R
        
# first system (should raise no exception)
K1=np.array([[2, 1, -4], [3, 3, -5], [4, 5, -2]], dtype=float)
L1=np.array([[8], [14], [16]], dtype=float)

# second system (should raise an exception)
K2=np.array([[0, 1, -4], [3, 3, -5], [4, 5, -2]], dtype=float)
L2=np.array([[8], [14], [16]], dtype=float)

# third system (issue with matrix size)
K3=np.array([[2, 1], [3, 3]], dtype=float)
L3=np.array([[8], [14], [16]], dtype=float)

try:
    gauss_jordan(K1, L1)
except ZeroDivisionError as err:
    print('run-time error:', err)
except AssertionError as err:
    print('run-time error:', err)  
       

On récupére les exceptions  __ZeroDivisionError__ et __AssertionError__, grace à un bloc try / except lors de l'appel de la fonction

In [10]:
#K=np.array([[0, 1, -4], [3, 3, -5], [4, 5, -2]], dtype=float)
#L=np.array([[8], [14], [16]], dtype=float)

K=np.array([[1, 1/4,  0, 0], 
            [1, 5/4, 12, 0], 
            [1, 1/3,  1, 1], 
            [1, 5/4, 13, 1]], dtype=float)
L=np.array([[0], [0], [1], [0]])

try:
    R=gauss_jordan(K, L)
except ZeroDivisionError as err:
    print('run-time error:', err)
    
K=np.array([[2, 1], [3, 3]], dtype=float)
L=np.array([[8], [14], [16]], dtype=float)
try:
    R=gauss_jordan(K, L)
    print(R)
except ZeroDivisionError as err:
    print('run-time error:', err)
except AssertionError as err:
    print('run-time error:', err)

run-time error: pivot akk trop faible
run-time error: number of rows not equal to 2


## 4. Gauss-Jordan avec pivot

On propose une nouvelle version de l'algorithme de Gauss-Jordan avec maximisation du pivot. Cette version permet de minimiser la propagation des erreurs d'arrondis et est donc plus robuste face aux problèmes de pivots de faibles valeurs. L'algorithme est itératif et s'effectue en $n$ étapes. A l'étape $k \in [0, n[$, on combine toutes les lignes sauf la ligne k pour faire apparaître des $0$ sur toute la colonne $k$ sauf au niveau du pivot $a_{kk}$. Par rapport à l'algorithme précédent, on procède de plus à un échange de ligne pour que le pivot de valeur maximale soit utilisé.

1. identifier l'indice de ligne $i \in [k, n[$  correspondant au $\max \{|a_{i,k}|\}$ 
2. échanger les lignes $i$ et $k$ de la matrice $A$
3. diviser ligne $k$ de la nouvelle matrice $A$ par $a_{kk}$
4. pour i=0 à n-1 sauf k :  retrancher à la ligne i, la nouvelle ligne k multipliée par $a_{ik}$
 
A faire :
1. Compléter la fonction 'gauss_jordan_pivot' pour implémenter l'algorithme présenté ci-dessus. Vous afficherez au fur et à mesure (pour chaque valeur de k) la matrice pour vérifier que les transformations successives se déroulent corectement.
2. Traiter le cas test précédent qui avait un problème de stabilité numérique.

In [10]:
import numpy as np
import math
np.set_printoptions(precision=4, suppress=False)

def gauss_jordan_pivot(A, B):
    n=A.shape[0]
    assert A.shape[1]==n, 'number of columns not equal to %r' % n
    assert B.shape[0]==n, 'number of rows not equal to %r' % n

    A=np.hstack((A, B)) # concaténation
    epsilon=1e-6
    
    for k in range(n):
        # Step 1
        colk=np.abs(A[k:, k])  # extraction de la sous colonne
        kmax=colk.argmax()+k   # offset k pour récupérer la vraie position
        print('colonne {:d}'.format(k))
#        if(k == kmax):
#            print('pas de modification :')
#        else:
#            print('avant : ')
#            print(A)
#            print('apres :')
        
        # Step 2
        A[[k, kmax]]=A[[kmax, k]] 
#        print(A)
            
        # Step 3
        akk=A[k, k]
        if abs(akk)<epsilon:
            raise ZeroDivisionError("pivot akk trop faible")
        A[k, :]=A[k, :]/akk

        # Step 4
        for i in range(n):
            if i==k: continue
            aik=A[i, k]
            A[i, :]=A[i, :]-aik*A[k, :]

    R=A[:, n:]
    return R

K=np.array([[1, 1/4,  0, 0], 
            [1, 5/4, 12, 0], 
            [1, 1/3,  1, 1], 
            [1, 5/4, 13, 1]], dtype=float)
L=np.array([[0], [0], [1], [0]])

try:
    R=gauss_jordan_pivot(K, L)
    print('resultat :')
    print(R)
except ZeroDivisionError as err:
    print('run-time error:', err)
    
print('Residu ----------')
print(L-(K @ R))


colonne 0
colonne 1
colonne 2
colonne 3
resultat :
[[-3.]
 [12.]
 [-1.]
 [ 1.]]
Residu ----------
[[0.]
 [0.]
 [0.]
 [0.]]


## 5. Résolution de systèmes mal conditionnés
 
 On examine ici l'influence d'une perturbation $\delta b$ sur les termes du second membre $b$ du  système d'équations linéaires. Il en résulte une variation $\delta x$ sur la solution. On montre par contre que $\delta x$ n'est pas forcément une perturbation de $x$ et dépend du conditionnement de $A$. On a l'inégalité suivante : 
 \begin{equation}
 \frac{|\delta x|}{|x|} < cond(A) \frac{|\delta b|}{|b|}
 \label{conderr}
 \end{equation}.
 
Le conditionnement est donné dans le cas d'une matrice symétrique par le rapport des valeurs propres  extrèmes en norme de $A$:
 $\kappa(A) = \frac{|\lambda_{max}(A)|}{|\lambda_{min}(A)|}$.
 
1. Résoudre le système d'équations en prenant :
 $A=\left(
\begin{array}{c c c c}
10  & 7   &   8 & 7  \\
7  &  5   & 6 & 5   \\
8  &  6  &  10   & 9  \\
7 & 5  & 9  &  10  
\end{array}
\right)$
et $B=\left(
\begin{array}{c c c c}
32  \\
23   \\
33  \\
31 
\end{array}
\right)$ 

2. Faites une fluctuation de $\pm 1\%$ sur le second membre et en déduire l'erreur sur la solution. 
3. Calculer le conditionnement de $A$ à partir de son spectre. On utilisera la fonction `numpy.linalg.eig()` pour calculer les valeurs propres.
4. Pour vérifier l'inégalité $\frac{|\delta x|}{|x|} < cond(A) \frac{|\delta b|}{|b|}$ ,  on calculera les normes avec la fonction `numpy.linalg.norm()` en choisissant une norme infinie, par exemple.

In [7]:
import numpy as np
import math

def gauss_jordan(A, B):
    n=A.shape[0]
    assert A.shape[1]==n, 'number of columns not equal to %r' % n
    assert B.shape[0]==n, 'number of rows not equal to %r' % n

    A=np.hstack((A, B)) # concaténation
    epsilon=1e-6
    for k in range(n):
        colk=np.abs(A[k:, k])
        kmax=colk.argmax()+k
        A[[k, kmax]]=A[[kmax, k]]      
        akk=A[k, k]
        if abs(akk)<epsilon:
            raise ZeroDivisionError("pivot akk trop faible")
        A[k, :]=A[k, :]/akk
#        print(A)
        for i in range(n):
            if i==k: continue
            aik=A[i, k]
            A[i, :]=A[i, :]-aik*A[k, :]
#        print('-----------')    
#        print(A)
    R=A[:, n:]
    return R

K=np.array([[10, 7,  8, 7], 
            [ 7, 5,  6, 5], 
            [ 8, 6,  10, 9], 
            [ 7, 5,  9, 10]], dtype=float)
L0=np.array([[32], [23], [33], [31]], dtype=float)

try:
    x0=gauss_jordan(K, L0)
    print('solution initiale')
    print(x0)
except ZeroDivisionError as err:
    print('run-time error:', err)
    
#print('Residu ----------')
#print(L-(K @ x0))
err=0.02*np.random.rand(4, 1)-0.01  # random error within +/- 1%
L=np.multiply(L0, 1+err) # element wise multiplication
#print(type(L))
try:
    x=gauss_jordan(K, L)
    print('solution second membre modifié')
    print(x)
except ZeroDivisionError as err:
    print('run-time error:', err)

print('solution linalg')
x=np.linalg.solve(K, L)
print(x)
lb, V=np.linalg.eig(K)
cond = np.abs(lb).max()/np.abs(lb).min()
print('conditionnement linalg.eig() : ', cond)
rx=np.linalg.norm(x-x0, ord=np.inf)/np.linalg.norm(x0, ord=np.inf)
rb=np.linalg.norm(L-L0, ord=np.inf)/np.linalg.norm(L0, ord=np.inf)
print('rapport : ', rx/rb)

solution initiale
[[1.]
 [1.]
 [1.]
 [1.]]
solution second membre modifié
[[-14.62515997]
 [ 26.78066314]
 [ -5.40572549]
 [  4.82627835]]
solution linalg
[[-14.62515997]
 [ 26.78066314]
 [ -5.40572549]
 [  4.82627835]]
conditionnement linalg.eig() :  2984.092701676514
rapport :  3419.280561917872


# Création d'une classe Matrix dérivant de np.ndarray
On veut utiliser l'opérateur * à la place de @ pour faire la multiplication de matrices.

La méthode __new__ est utilisée ici car on dérive une classe à partir d’un type immutable comme numpy.ndarray, et dans ce cas c’est __new__ (et non __init__) qui est responsable de la création de l’objet.


In [15]:
import numpy as np

class Matrix(np.ndarray):
    # La méthode __new__ est utilisée ici car on dérive une classe à partir d’un type immutable 
    # comme numpy.ndarray, et dans ce cas c’est __new__ (et non __init__) qui est responsable de la création de l’objet.
    def __new__(cls, input_array, dtype=None):
        # Convertit le tableau d'entrée en np.ndarray avec le bon dtype
        obj = np.asarray(input_array, dtype=dtype).view(cls)
        return obj

    def __mul__(self, other):
        if isinstance(other, (Matrix, np.ndarray)):
            return Matrix(np.matmul(self, other))
    
    def __rmul__(self, other):
        return Matrix(np.matmul(other, self))

    def __repr__(self):
        return f"Matrix({super().__repr__()})"

A = Matrix([[1, 2, 3], 
            [4, 5, 6]], dtype=float)    # 2x3
B = Matrix([[7, 8], [9, 10], [11, 12]], dtype=int)  # 3x2

C = A * B   # produit matriciel 2x2
print(C-A@B)

[[0. 0.]
 [0. 0.]]


In [13]:
import numpy as np
import math
np.set_printoptions(precision=4, suppress=False)

def gauss_jordan_pivot(A, B):
    n=A.shape[0]
    assert A.shape[1]==n, 'number of columns not equal to %r' % n
    assert B.shape[0]==n, 'number of rows not equal to %r' % n

    A=np.hstack((A, B)) # concaténation
    epsilon=1e-6
    
    for k in range(n):
        # Step 1
        colk=np.abs(A[k:, k])  # extraction de la sous colonne
        kmax=colk.argmax()+k   # offset k pour récupérer la vraie position
        print('colonne {:d}'.format(k))
#        if(k == kmax):
#            print('pas de modification :')
#        else:
#            print('avant : ')
#            print(A)
#            print('apres :')
        
        # Step 2
        A[[k, kmax]]=A[[kmax, k]] 
#        print(A)
            
        # Step 3
        akk=A[k, k]
        if abs(akk)<epsilon:
            raise ZeroDivisionError("pivot akk trop faible")
        A[k, :]=A[k, :]/akk

        # Step 4
        for i in range(n):
            if i==k: continue
            aik=A[i, k]
            A[i, :]=A[i, :]-aik*A[k, :]

    R=A[:, n:]
    return R

K=Matrix([[1, 1/4,  0, 0], 
            [1, 5/4, 12, 0], 
            [1, 1/3,  1, 1], 
            [1, 5/4, 13, 1]], dtype=float)
L=Matrix([[0], [0], [1], [0]])

try:
    R=gauss_jordan_pivot(K, L)
    print('resultat :')
    print(R)
except ZeroDivisionError as err:
    print('run-time error:', err)
    
print('Residu ----------')
print(L-(K * R))


colonne 0
colonne 1
colonne 2
colonne 3
resultat :
[[-3.]
 [12.]
 [-1.]
 [ 1.]]
Residu ----------
[[0.]
 [0.]
 [0.]
 [0.]]
