## factorisation LU
On se propose d'implémenter la méthode de décomposition LU avec changement de pivot

La classe  numpy.ndarray permet de créer des tableaux multi-dimensionnels. 

* En particulier, on notera que l'opérateur * définit une multiplication du type élément par élément (element-wise multiplication)
* Pour des tableaux bidimensionnels pouvant stocker des matrices et des vecteurs, l'opérateur @ sert à faire la multiplication matricielle.

La classe numpy.matrix dérive de la classe  numpy.ndarray mais est considérée comme obsolète.

In [2]:
#**
# VOIR LA CELLULE CI-APRES POUR CORRECTION OFFICIELLE
#**

# A : matrice a factoriser de dim nxn  
import numpy as np
np.set_printoptions(precision=4, suppress=True)

def LU(A):
    """factorisation LU avec pivot"""
    assert A.shape[0]==A.shape[1], 'not a square matrix' 
    n=A.shape[0]
    PL=np.eye(n, n) # Matrice Identite
    P =np.eye(n, n)
    Lp=np.eye(n, n)
    
    for k in range(n-1):
# Construction de la matrice de permutation
        Pk    = np.eye(n, n)
        colk=np.abs(A[k:, k])
        print(colk)
        kmax=colk.argmax()+k # ATTENTION offset
        Pk[[k, kmax]]=Pk[[kmax, k]]
        A=Pk.dot(A)

# Construction de la matrice d’elimination
        inv_Lk= np.eye(n, n)
        for i in range(k+1, n):
            inv_Lk[i,k]=-A[i,k]/A[k,k];

# Construction de la matrice A(k+1) a partir de A(k) 
        A=inv_Lk.dot(A)
        Lk=-inv_Lk+2*np.eye(n, n) # Inverse de la matrice d’elimination
        Lp=Lp.dot(Lk)
        PLk=Pk.dot(Lk)
        PL=PL.dot(PLk)
        print('Pk : \n', Pk)
        P=P.dot(Pk) # Pk @ Pk = Id
        print('P : \n', P)
        print('Pk*Pk')
        print(np.dot(Pk, Pk))
# matrice A(k+1) est la matrice triangulaire superieure
    U=A
    inv_P=P.T
    L=inv_P.dot(PL)
    
    return P, L, U


 
A=np.array([[10, -7, 0], [-3, 2, 6], [5, -1, 5]], dtype=float)  
P, L, U = LU(A)

print('P ---------')
print(P)

print('L-----------')
print(L)
print('U-----------')
print(U)


[10.  3.  5.]
Pk : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
P : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Pk*Pk
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.1 2.5]
Pk : 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
P : 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
Pk*Pk
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
P ---------
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L-----------
[[ 1.    0.    0.  ]
 [ 0.5   1.    0.  ]
 [-0.3  -0.04  1.  ]]
U-----------
[[10.  -7.   0. ]
 [ 0.   2.5  5. ]
 [ 0.   0.   6.2]]
